name:                language-ruby
version:             0.1.0.0
github:              "githubuser/language-ruby"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/language-ruby#readme>

dependencies:
- base >= 4.7 && < 5
- array
- utf8-string
- containers

library:
  source-dirs: src
  dependencies:
    - mtl
  build-tools:
    - happy
    - alex

tests:
  language-ruby-test:
    main:                Spec.hs
    source-dirs:         spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-missing-signatures
    - -fno-warn-unused-do-bind
    - -fno-warn-orphans
    - -fno-warn-name-shadowing
    - -fno-warn-incomplete-patterns
    - -fno-warn-missing-pattern-synonym-signatures
    - -fwarn-tabs
    - -funbox-strict-fields
    dependencies:
    - hspec
    - language-ruby
